=== horpia/srv-tree/build/data/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="service">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="desc" minOccurs="0"/>
				<xs:element name="ip" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="global-addr" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="local-addr" minOccurs="0" maxOccurs="unbounded"/>
			</xs:choice>
			<xs:attribute name="type" type="xs:string"/>
			<xs:attribute name="name" type="xs:string"/>
			<xs:attribute name="port" type="xs:positiveInteger"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="include">
		<xs:complexType>
			<xs:attribute name="src" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="srv">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="ip" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="global-addr" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="local-addr" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="desc" minOccurs="0"/>
				<xs:element name="cpu" minOccurs="0"/>
				<xs:element name="ram" minOccurs="0"/>
				<xs:element name="disk" minOccurs="0"/>
				<xs:element name="os" minOccurs="0"/>
				<xs:element ref="service" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="vm" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="desc" minOccurs="0"/>
							<xs:element ref="service" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="ip" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="global-addr" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element name="local-addr" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:choice>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="infra">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="dc" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded">
							<xs:element name="desc" minOccurs="0"/>
							<xs:element ref="srv" minOccurs="0" maxOccurs="unbounded"/>
							<xs:element ref="include" minOccurs="0" maxOccurs="unbounded"/>
						</xs:choice>
						<xs:attribute name="name" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== horpia/srv-tree/build/data/servers/dsru231.xml
<?xml version="1.0" encoding="utf-8" ?>
<srv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd"
	 name="dsru231" ip="192.168.1.100">
	<desc>Server for prod purposes</desc>
	<cpu>Xeon Silver 4110</cpu>
	<ram>16GB</ram>
	<disk>2 x 2 TB SSD</disk>
	<os>CentOS 7</os>
	<vm ip="192.168.1.101" name="vm1">
		<service type="php"/>
		<service type="rabbitmq" port="5672"/>
		<service type="kafka" port="2181"/>
	</vm>
	<vm ip="192.168.1.102" name="vm2">
		<service type="redis" port="8796"/>
		<service type="crontab"/>
	</vm>
</srv>

=== horpia/srv-tree/public/data/servers/backup1.xml
<?xml version="1.0" encoding="utf-8" ?>
<srv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd"
	name="backup1" ip="192.168.10.1">
	<desc>Server for prod purposes</desc>
	<cpu>Xeon Silver 4110</cpu>
	<ram>16GB</ram>
	<disk>2 x 2 TB SSD</disk>
	<os>CentOS 7</os>
	<service type="nginx" port="80" domain="backup-example.com"/>
	<service name="Backup Engine"/>
	<service type="storage"/>
</srv>

=== horpia/srv-tree/public/data/servers/dsde375.xml
<?xml version="1.0" encoding="utf-8" ?>
<srv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd"
	 name="dsde375" ip="192.168.10.1">
	<desc>Server for prod purposes</desc>
	<cpu>Xeon Silver 4110</cpu>
	<ram>16GB</ram>
	<disk>2 x 2 TB SSD</disk>
	<os>CentOS 7</os>
	<service type="nginx" port="80" domain="example.com,example1.com,example2.com"/>
	<vm ip="192.168.10.2" name="php-vm1" local-domain="php1.example.ru">
		<service type="php-fpm" port="9000"/>
		<service type="redis" name="Redis single node" port="6379">
			<desc>R/W User sessions and common info. Master only.</desc>
		</service>
		<service type="redis" name="Redis Cluster" port="6378">
			<desc>Cache layer for MySQL</desc>
		</service>>
	</vm>
	<vm ip="192.168.10.3" name="php-vm2" local-domain="php2.example.ru">
		<service type="php-fpm" port="9000"/>
		<service type="apache" port="8080"/>
		<service type="mysql" name="MySQL Master" port="3306"/>
		<service type="redis" name="Local Redis" port="6379">
			<desc>Local Redis single instance for cron jobs</desc>
		</service>
	</vm>
	<vm ip="192.168.10.4" name="db-vm1">
		<desc>VM for secondary databases. Fault tolerance. Can be turned off at any time</desc>
		<service type="sphinxsearch" port="9312"/>
		<service type="elasticsearch" port="9312"/>
		<service type="postgresql" port="5432"/>
		<service type="mariadb" port="3306"/>
		<service type="oracle" port="1521"/>
		<service type="mongodb" port="27017"/>
		<service type="mssql" port="1433"/>
		<service type="db2" port="50000"/>
	</vm>
</srv>

=== horpia/srv-tree/public/data/servers/dsde432.xml
<?xml version="1.0" encoding="utf-8" ?>
<srv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd"
	 name="dsde432">
	<ip>192.168.10.5</ip>
	<desc>Server for data analytics</desc>
	<cpu>Xeon Silver 4110</cpu>
	<ram>16GB</ram>
	<disk>2 x 2 TB SSD</disk>
	<os>CentOS 7</os>
	<vm name="nodejs-vm1">
		<ip>192.168.10.6</ip>
		<local-addr>node1.example.ru</local-addr>
		<service type="nodejs" port="7731">
			<global-addr>a.example.com</global-addr>
			<desc>NodeJS server</desc>
		</service>
		<service type="cassandra" port="7000"/>
		<service type="clickhouse" port="9000"/>
	</vm>
	<vm name="dockers-vm">
		<ip>192.168.10.7</ip>
		<service type="mysql" name="MySQL Slave" port="3306"/>
		<service type="docker" name="Data processing microservice"/>
		<service type="consul" port="8500"/>
		<service type="jenkins" name="Jenkins">
			<local-addr>jenkins.example.com</local-addr>
		</service>
		<service type="kibana" name="Kibana">
			<local-addr>kibana.example.com</local-addr>
		</service>
		<service type="zabbix">
			<local-addr>zabbix.example.com</local-addr>
		</service>
		<service type="mysql" name="PhpMyAdmin">
			<local-addr>pma.example.com</local-addr>
		</service>
	</vm>
</srv>

=== horpia/srv-tree/build/data/data.xml
<?xml version="1.0" encoding="utf-8" ?>
<infra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <dc name="Data Center #1">
		<desc>Some description about this Data Center...</desc>
        <include src="servers/dsde375.xml"/>
        <include src="servers/dsde432.xml"/>
    </dc>
	<dc name="Data Center #2">
		<desc>Some description about this Data Center...</desc>
        <include src="servers/backup1.xml"/>
        <include src="servers/dsru231.xml"/>
    </dc>
</infra>

=== horpia/srv-tree/public/data/servers/dsru231.xml
<?xml version="1.0" encoding="utf-8" ?>
<srv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schema.xsd"
	 name="dsru231">
	<ip>192.168.1.100</ip>
	<desc>Server for prod purposes</desc>
	<cpu>Xeon Silver 4110</cpu>
	<ram>16GB</ram>
	<disk>2 x 2 TB SSD</disk>
	<os>CentOS 7</os>
	<vm name="vm1">
		<ip>192.168.1.101</ip>
		<service type="php"/>
		<service type="rabbitmq" port="5672"/>
		<service type="kafka" port="2181"/>
		<service type="graylog">
			<global-addr>graylog.example.com</global-addr>
		</service>
	</vm>
	<vm name="vm2">
		<ip>192.168.1.102</ip>
		<service type="redis" port="8796"/>
		<service type="crontab"/>
	</vm>
	<vm name="vm3">
		<ip>192.168.1.103</ip>
		<service type="java" name="Service">
			<local-addr>app1.example.com</local-addr>
		</service>
		<service type="python" name="App 1"/>
		<service type="ruby" name="App 2"/>
		<service type="perl" name="App 3"/>
	</vm>
</srv>

=== horpia/srv-tree/public/data/data.xml
<?xml version="1.0" encoding="utf-8" ?>
<infra xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd">
    <dc name="Fornex - DE">
		<desc>
			ЦОД в Германии. Основные сервера сайта
		</desc>
        <srv name="dsde321" ip="192.168.10.12" domain="pikabu.ru">
			<cpu>Xenon 12321</cpu>
			<disk>27TB SSD (Raid 4)</disk>
			<service type="redis" port="8976"/>
            <vm ip="192.168.10.1" name="php-vm1">
				<service type="php-fpm" port="3000"/>
			</vm>
            <vm ip="192.168.10.2" name="php-vm2" domain="pikabu.ru">
				<service type="nginx" port="80" domain="pikabu.ru"/>
				<service type="php-fpm" port="3000"/>
				<service type="mysql" port="3234" local-domain="adm.staff.pikabu.ru"/>
				<service type="cassandra" port="1234"/>
				<service type="rabbitmq" port="1234"/>
				<service type="sphinx" port="1234"/>
				<service type="elasticsearch" port="1234"/>
				<service type="clickhouse" port="1234"/>
				<service type="docker"/>
				<service type="nodejs"/>
				<service type="kafka"/>
			</vm>
        </srv>
		<srv name="dsde31" ip="192.168.10.12" domain="pikabu.ru">
		</srv>
    </dc>
</infra>
